//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFilmy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.Movie_Instance = new HashSet<Movie_Instance>();
        }
    
        public int ID_Movie { get; set; }
        public string Title { get; set; }
        public string Director { get; set; }
        public Nullable<System.DateTime> Relase_Date { get; set; }
        public string Category { get; set; }
        public Nullable<int> Year_Limitation { get; set; }
        public Nullable<int> Penalty { get; set; }
        public Nullable<int> Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movie_Instance> Movie_Instance { get; set; }
    }
}
