//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFilmy
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoviesRentedByAUser
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Title { get; set; }
        public Nullable<bool> Is_Rented { get; set; }
        public Nullable<System.DateTime> rental_date { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Penalty { get; set; }
        public int ID_client { get; set; }
    }
}
