//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFilmy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int ID_Transactions { get; set; }
        public Nullable<int> FK_ID_Movie_Instance { get; set; }
        public Nullable<int> FK_ID_Clients { get; set; }
        public Nullable<System.DateTime> rental_date { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Movie_Instance Movie_Instance { get; set; }
    }
}
